from UK_Utilities import *

T0, Pop, C_Coal, C_Oil, C_Gas, P_Coal, P_Oil, P_Gas = Load_Calibrations_UK()

P1 = Population_UK()
P1.Solve( np.linspace( 1800, 2100, 301))
C0 = Coal_UK_Cons()
C0.Solve( np.linspace( 1800, 2100, 301))
#C0.Solve( np.linspace( 2015, 2100, 86))
C1 = Oil_UK_Cons()
C1.Solve( np.linspace( 1800, 2100, 301))
#C1.Solve( np.linspace( 2015, 2100, 86))
C2 = Gas_UK_Cons()
C2.Solve( np.linspace( 1800, 2100, 301))
#C2.Solve( np.linspace( 2015, 2100, 86))

fig = plt.figure( figsize=(15,10))
plt.plot( C0.Time, C0.Total, "-", lw=2, color="k", label="Потребление угля (модель)")
plt.plot( C1.Time, C1.Total, "-", lw=2, color="g", label="Потребление нефти (модель)")
plt.plot( C2.Time, C2.Total, "-", lw=2, color="r", label="Потребление газа (модель)")
plt.errorbar( T0, C_Coal, yerr=5, fmt='.', color="k", label="Потребление угля (BP+Халл)")
plt.errorbar( T0, C_Oil, yerr=5, fmt='.', color="g", label='Потребление нефти и "жидкостей" (BP)')
plt.errorbar( T0, C_Gas, yerr=5, fmt='.', color="r", label="Потребление газа (статистика BP)")
plt.xlabel("Годы")
plt.xlim( 1850, 2100)
plt.ylabel("Миллионов тонн нефтяного эквивалента")
plt.ylim( 0, 250)
plt.title( 'Потребление угля, нефти и газа Великобританией')
plt.grid(True)
plt.legend(loc=0)
plt.savefig( "./Graphs/figure_12_03.png")
if InteractiveModeOn: plt.show(True)
