from UK_Utilities import *

T0, Pop, C_Coal, C_Oil, C_Gas, P_Coal, P_Oil, P_Gas, C_Nuc, C_Hyd, C_Ren, C_Tot = Load_Calibrations_UK_Full()

P1 = Population_UK()
P1.Solve( np.linspace( 1800, 2100, 301))
C0 = Coal_UK_Cons()
C0.Solve( np.linspace( 1800, 2100, 301))
C1 = Oil_UK_Cons()
C1.Solve( np.linspace( 1800, 2100, 301))
C2 = Gas_UK_Cons()
C2.Solve( np.linspace( 1800, 2100, 301))
C3 = Nuc_UK_Cons()
C3.Solve( np.linspace( 1800, 2100, 301))
C4 = Hydro_UK_Cons()
C4.Solve( np.linspace( 1800, 2100, 301))
C5 = Renewable_UK_Cons()
C5.Solve( np.linspace( 1800, 2100, 301))

fig = plt.figure( figsize=(15,10))
plt.plot( C3.Time, C3.Total, "-", lw=2, color="m", label="Потребление ядерной энергии (модель)")
plt.plot( C4.Time, C4.Total, "-", lw=2, color="b", label="Потребление гидро энергии (модель)")
plt.plot( C5.Time, C5.Total, "-", lw=2, color="y", label="Потребление возобновляемой кроме гидро")
plt.errorbar( T0, C_Nuc, yerr=1, fmt='.', color="m", label="Выработка ядерной энергии (BP)")
plt.errorbar( T0, C_Hyd, yerr=1, fmt='.', color="b", label='Выработка гидро энергии (BP)')
plt.errorbar( T0, C_Ren, yerr=1, fmt='.', color="y", label="Возобновляемые кроме гидро")
plt.xlabel("Годы")
plt.xlim( 1850, 2100)
plt.ylabel("Миллионов тонн нефтяного эквивалента")
plt.ylim( 0, 50)
plt.title( 'Потребление ядерной и возобновляемой энергии Великобританией')
plt.grid(True)
plt.legend(loc=0)
plt.savefig( "./Graphs/figure_12_04.png")
fig.show()
